server:
  port: 9999
spring:
  datasource:
    url: jdbc:oracle:thin:@repick.synology.me:31521:XE
    username: jpa
    password: jpa123
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    hibernate:
      ddl-auto: create